(function(){
  'use strict';
  const config=window.KAVOR_ACCOUNT_CONFIG||{};
  if(!config.supabaseUrl||!config.publishableKey||document.querySelector('.kavora-chat'))return;
  const endpoint=`${config.supabaseUrl}/functions/v1/kavora-chat`;
  const language=(document.documentElement.lang||navigator.language||'sv').slice(0,2).toLowerCase();
  const copy={
    sv:{title:'Kavora Kundhjälp',subtitle:'Digital assistent',hello:'Hej! Jag är Kavora, Kavors digitala assistent. Vad kan jag hjälpa dig med?',placeholder:'Skriv din fråga…',send:'Skicka',contact:'Kontakta Claudio',privacy:'Vanlig chatt sparas inte.',safety:'Vid gaslukt, rök, brandrisk eller skadade elkablar: avbryt, stäng av gasol och 230 V om det kan göras säkert och kontakta behörig hjälp.',quick:['Hur fungerar Kavor?','Konto eller licens','Pris och provperiod'],formTitle:'Be om personlig hjälp',formText:'Dina kontaktuppgifter och chatten sparas bara när du skickar detta ärende.',name:'Namn',email:'E-post',subject:'Vad gäller det?',consent:'Jag godkänner att Kavor sparar uppgifterna för att besvara mitt ärende.',submit:'Skicka ärendet',sent:'Tack! Ärendet är skickat till Claudio.',failed:'Det gick inte att skicka. Mejla info@kavor.se.'},
    en:{title:'Kavora Support',subtitle:'Digital assistant',hello:'Hi! I am Kavora, Kavor’s digital assistant. How can I help?',placeholder:'Type your question…',send:'Send',contact:'Contact Claudio',privacy:'Regular chat is not stored.',safety:'If you smell gas or notice smoke, fire risk or damaged wiring: stop, turn off gas and 230 V if safe, and contact qualified help.',quick:['How does Kavor work?','Account or licence','Price and free trial'],formTitle:'Ask for personal help',formText:'Your contact details and chat are saved only when you submit this request.',name:'Name',email:'Email',subject:'What is it about?',consent:'I agree that Kavor stores the information to answer my request.',submit:'Send request',sent:'Thank you! Your request was sent to Claudio.',failed:'Could not send. Email info@kavor.se.'},
    es:{title:'Ayuda Kavora',subtitle:'Asistente digital',hello:'¡Hola! Soy Kavora, el asistente digital de Kavor. ¿En qué puedo ayudarte?',placeholder:'Escribe tu pregunta…',send:'Enviar',contact:'Contactar con Claudio',privacy:'El chat normal no se guarda.',safety:'Si huele a gas o hay humo, riesgo de incendio o cables dañados: detente, corta el gas y 230 V si es seguro y contacta con personal cualificado.',quick:['¿Cómo funciona Kavor?','Cuenta o licencia','Precio y prueba gratuita'],formTitle:'Pedir ayuda personal',formText:'Tus datos de contacto y el chat solo se guardan al enviar esta solicitud.',name:'Nombre',email:'Correo electrónico',subject:'¿De qué se trata?',consent:'Acepto que Kavor guarde los datos para responder a mi solicitud.',submit:'Enviar solicitud',sent:'¡Gracias! La solicitud fue enviada a Claudio.',failed:'No se pudo enviar. Escribe a info@kavor.se.'}
  }[language]||null;
  const t=copy||{
    title:'Kavora Kundhjälp',subtitle:'Digital assistent',hello:'Hej! Jag är Kavora, Kavors digitala assistent. Vad kan jag hjälpa dig med?',placeholder:'Skriv din fråga…',send:'Skicka',contact:'Kontakta Claudio',privacy:'Vanlig chatt sparas inte.',safety:'Vid gaslukt, rök, brandrisk eller skadade elkablar: avbryt och kontakta behörig hjälp.',quick:['Hur fungerar Kavor?','Konto eller licens','Pris och provperiod'],formTitle:'Be om personlig hjälp',formText:'Uppgifterna sparas bara när du skickar ärendet.',name:'Namn',email:'E-post',subject:'Vad gäller det?',consent:'Jag godkänner lagringen för att få svar.',submit:'Skicka ärendet',sent:'Ärendet är skickat.',failed:'Det gick inte att skicka. Mejla info@kavor.se.'
  };
  const idKey='kavora_chat_session';
  let sessionId=localStorage.getItem(idKey);
  if(!sessionId){sessionId=crypto.randomUUID();localStorage.setItem(idKey,sessionId)}
  let messages=[];
  try{messages=JSON.parse(sessionStorage.getItem('kavora_chat_messages')||'[]')}catch{messages=[]}
  const root=document.createElement('aside');root.className='kavora-chat';root.setAttribute('aria-label',t.title);
  root.innerHTML=`<button class="kavora-launcher" type="button" aria-expanded="false"><span>✦</span><span>${t.title}</span></button><section class="kavora-panel" hidden><header class="kavora-head"><div><strong>${t.title}</strong><small>${t.subtitle}</small></div><button class="kavora-close" type="button" aria-label="Stäng">×</button></header><div class="kavora-body" aria-live="polite"></div><div class="kavora-compose"><form class="kavora-form"><textarea maxlength="800" rows="1" placeholder="${t.placeholder}" aria-label="${t.placeholder}" required></textarea><button type="submit" aria-label="${t.send}">➤</button></form><div class="kavora-foot"><small>${t.privacy}</small><button class="kavora-contact-button" type="button">${t.contact}</button></div></div></section>`;
  document.body.appendChild(root);
  const launcher=root.querySelector('.kavora-launcher'),panel=root.querySelector('.kavora-panel'),body=root.querySelector('.kavora-body'),form=root.querySelector('.kavora-form'),input=form.querySelector('textarea'),contactButton=root.querySelector('.kavora-contact-button');
  function save(){sessionStorage.setItem('kavora_chat_messages',JSON.stringify(messages.slice(-12)))}
  function add(role,text,remember=true){const item=document.createElement('div');item.className=`kavora-message ${role}`;item.textContent=text;body.appendChild(item);if(remember&&['user','assistant'].includes(role)){messages.push({role,content:text});messages=messages.slice(-12);save()}body.scrollTop=body.scrollHeight}
  function showWelcome(){if(messages.length){messages.forEach(item=>add(item.role,item.content,false));return}add('assistant',t.hello);const quick=document.createElement('div');quick.className='kavora-quick';quick.innerHTML=t.quick.map(text=>`<button type="button">${text}</button>`).join('');quick.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>sendMessage(button.textContent)));body.appendChild(quick);const safety=document.createElement('div');safety.className='kavora-safety';safety.textContent=t.safety;body.appendChild(safety)}
  async function request(payload){const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',apikey:config.publishableKey},body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Request failed');return data}
  async function sendMessage(text){text=String(text||'').trim();if(!text)return;add('user',text);input.value='';const typing=document.createElement('div');typing.className='kavora-typing';typing.textContent='Kavora skriver…';body.appendChild(typing);body.scrollTop=body.scrollHeight;try{const data=await request({action:'chat',sessionId,language,messages:messages.slice(-10)});typing.remove();add('assistant',data.reply||t.failed)}catch(error){typing.remove();add('error',t.failed,false)}}
  function showContact(){if(body.querySelector('.kavora-contact')){body.querySelector('.kavora-contact input')?.focus();return}const box=document.createElement('form');box.className='kavora-contact';box.innerHTML=`<h3>${t.formTitle}</h3><p>${t.formText}</p><label>${t.name}<input name="name" maxlength="100" required></label><label>${t.email}<input name="email" type="email" maxlength="200" required></label><label>${t.subject}<textarea name="subject" maxlength="1000" rows="3" required></textarea></label><label class="kavora-consent"><input name="consent" type="checkbox" required><span>${t.consent}</span></label><button class="kavora-contact-submit" type="submit">${t.submit}</button><div class="kavora-contact-status" role="status"></div>`;box.addEventListener('submit',async event=>{event.preventDefault();const status=box.querySelector('.kavora-contact-status'),button=box.querySelector('button');button.disabled=true;status.textContent='…';const data=new FormData(box);try{await request({action:'handoff',sessionId,language,name:data.get('name'),email:data.get('email'),subject:data.get('subject'),consent:data.get('consent')==='on',messages:messages.slice(-12)});status.textContent=t.sent;box.reset()}catch{status.textContent=t.failed}finally{button.disabled=false}});body.appendChild(box);body.scrollTop=body.scrollHeight;box.querySelector('input')?.focus()}
  function toggle(open){panel.hidden=!open;launcher.setAttribute('aria-expanded',String(open));document.documentElement.classList.toggle('kavora-panel-open',open&&matchMedia('(max-width:520px)').matches);if(open)input.focus()}
  launcher.addEventListener('click',()=>toggle(panel.hidden));root.querySelector('.kavora-close').addEventListener('click',()=>toggle(false));contactButton.addEventListener('click',showContact);form.addEventListener('submit',event=>{event.preventDefault();sendMessage(input.value)});input.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();form.requestSubmit()}});
  showWelcome();
})();
